fix: workflow

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,32 +4,32 @@
 # Load config (variables)
 . "$(dirname -- "$0")/config.sh"
 
-echo ""
-echo "${BLUE}INFO${NC}: Running ${YELLOW}pre-commit${NC} hook"
+# echo ""
+# echo "${BLUE}INFO${NC}: Running ${YELLOW}pre-commit${NC} hook"
 
-echo ""
-echo "${GREEN}INFO${NC}: ${YELLOW}Installing all dependencies${NC}"
-pnpm install --no-frozen-lockfile 1>/dev/null
-git add pnpm-lock.yaml
+# echo ""
+# echo "${GREEN}INFO${NC}: ${YELLOW}Installing all dependencies${NC}"
+# pnpm install --no-frozen-lockfile 1>/dev/null
+# git add pnpm-lock.yaml
 
-echo ""
-echo "${GREEN}INFO${NC}: ${YELLOW}Formatting code${NC}"
-pnpm format 1>/dev/null
+# echo ""
+# echo "${GREEN}INFO${NC}: ${YELLOW}Formatting code${NC}"
+# pnpm format 1>/dev/null
 
-echo ""
-echo "${GREEN}INFO${NC}: ${YELLOW}Checking for unstaged changes${NC}"
-if ! git diff --quiet --exit-code; then
-    echo "${RED}ERROR${NC}: ${RED}There are unstaged changes${NC}."
-    echo "${BLUE}INFO${NC}: ${YELLOW}Please stage your changes.${NC}"
-    echo "${BLUE}INFO${NC}: ${YELLOW}Commit aborted.${NC}"
-    exit 1
-fi
+# echo ""
+# echo "${GREEN}INFO${NC}: ${YELLOW}Checking for unstaged changes${NC}"
+# if ! git diff --quiet --exit-code; then
+#     echo "${RED}ERROR${NC}: ${RED}There are unstaged changes${NC}."
+#     echo "${BLUE}INFO${NC}: ${YELLOW}Please stage your changes.${NC}"
+#     echo "${BLUE}INFO${NC}: ${YELLOW}Commit aborted.${NC}"
+#     exit 1
+# fi
 
-echo ""
-echo "${GREEN}INFO${NC}: ${YELLOW}Checking for branch${NC}"
-if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
-    echo "${RED}ERROR${NC}: ${RED}you are on master${NC}."
-    echo "${BLUE}INFO{NC}: ${YELLOW}Please checkout to another branch.${NC}"
-    echo "${BLUE}INFO${NC}: ${YELLOW}Commit aborted.${NC}"
-    exit 1
-fi
+# echo ""
+# echo "${GREEN}INFO${NC}: ${YELLOW}Checking for branch${NC}"
+# if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
+#     echo "${RED}ERROR${NC}: ${RED}you are on master${NC}."
+#     echo "${BLUE}INFO{NC}: ${YELLOW}Please checkout to another branch.${NC}"
+#     echo "${BLUE}INFO${NC}: ${YELLOW}Commit aborted.${NC}"
+#     exit 1
+# fi
